START TRANSACTION;

INSERT INTO `categories` (`category_name`) VALUES

('Aerodynamics of Flight'),
('Aeromedical Factors'),
('Aeronautical Decision-Making'),
('Aircraft Buying Guides'),
('Aircraft Design'),
('Aircraft Docs & Flight Manuals'),
('Aircraft Maintenance and Care'),
('Aircraft Systems'),
('Airmen Certification'),
('Airport Equipment'),
('Airport Operations'),
('Airspace'),
('Airworthiness Standards'),
('Aviation Calculations'),
('Aviation Case Studies'),
('Aviation History'),
('Aviation Organizations'),
('Aviation Weather Services'),
('Basic Instrument Maneuvers'),
('Beginning Flight'),
('Career Development'),
('Checkride Preparation'),
('Cockpit Management'),
('Emergency Operations'),
('Flight Controls'),
('Flight Instruments'),
('Flight Planning'),
('Flight Safety'),
('Flight Simulation'),
('Ground Operations'),
('Health and Wellness'),
('Maneuvers'),
('Multiengine Operations'),
('Navigation'),
('Navigation Systems'),
('Night Operations'),
('Performance and Limitations'),
('Postflight Procedures'),
('Preflight Procedures'),
('Radio Communications'),
('Regulations and Guidelines'),
('Risk Management'),
('Seaplane Base Operations'),
('Slow Flight and Stalls'),
('Special Flight Operations'),
('Takeoffs, Landings, and Go-Arounds'),
('Weather Theory'),
('Weight and Balance');

COMMIT;
